#
# Builder stage.
#
FROM node:16 AS builder

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./tsconfig*.json ./
COPY . .

RUN npm i --quiet

# #
# # Production stage.
# #
# FROM node:16-alpine

# WORKDIR /app
# ENV NODE_ENV=production
# ENV NODE_PATH=dist

# COPY package*.json .

# RUN npm i --quiet --only=production --omit=dev

# COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3000
